### ISSUE TITLE
Idk what to do

### ISSUE THREAD

**Issue by BabyRexPlayz** [MassinissaAchour/All-In-One-Bot#9]
I put ng token and clicked "run" and this is what it respondent what to do

> All-In-One-Bot@1.0.0 start /home/runner/All-In-One-Bot
> node %NODE_DEBUG_OPTION% .

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/runner/All-In-One-Bot/%NODE_DEBUG_OPTION%'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! All-In-One-Bot@1.0.0 start: `node %NODE_DEBUG_OPTION% .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the All-In-One-Bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-12T10_15_36_531Z-debug.log
exit status 1
 ^C
 ^C
 npm start

> All-In-One-Bot@1.0.0 start /home/runner/All-In-One-Bot
> node %NODE_DEBUG_OPTION% .

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/runner/All-In-One-Bot/%NODE_DEBUG_OPTION%'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! All-In-One-Bot@1.0.0 start: `node %NODE_DEBUG_OPTION% .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the All-In-One-Bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-12T10_19_09_271Z-debug.log

**Comment by SpreeHertz** [comment]
![image](https://user-images.githubusercontent.com/48062454/139375772-bb937cb9-dba9-47ed-ace4-d9ea22d2fa93.png)

**Comment by BabyRexPlayz** [comment]
What module am I missing idk?

**Comment by SpreeHertz** [comment]
Wait, do you have the latest version of node.js installed? It must be v16 or higher.

**Comment by BabyRexPlayz** [comment]
I am using replit to run that what do I install?

**Comment by SpreeHertz** [comment]
I am sorry. I do not like using replit nor do I recommend using replit. I recommend you use a proper IDE like VSCode.

**Comment by BabyRexPlayz** [comment]
ok I downloaded VSCode now what do I install?

**Comment by SpreeHertz** [comment]
Go to [Node.js](https://nodejs.org) and download the latest version of Node.js. Try running this bot again
